-- SpoolShare filament catalog seed. Generated from src/lib/api/mock/seed/catalog.ts
-- Run after schema.sql. Safe to re-run (upserts).

insert into manufacturers (id, name, website) values
  ('bambu', 'Bambu Lab', 'https://bambulab.com'),
  ('polymaker', 'Polymaker', 'https://polymaker.com'),
  ('prusament', 'Prusament', 'https://prusament.com'),
  ('hatchbox', 'Hatchbox', 'https://hatchbox3d.com'),
  ('esun', 'eSUN', 'https://esun3d.com'),
  ('overture', 'Overture', 'https://overture3d.com'),
  ('elegoo', 'Elegoo', 'https://elegoo.com'),
  ('sunlu', 'Sunlu', 'https://sunlu.com')
on conflict (id) do update set name = excluded.name, website = excluded.website;

insert into product_lines (id, manufacturer_id, name, material, finish) values
  ('bambu-pla-basic', 'bambu', 'PLA Basic', 'PLA', 'basic'),
  ('bambu-pla-matte', 'bambu', 'PLA Matte', 'PLA', 'matte'),
  ('bambu-pla-silk', 'bambu', 'PLA Silk+', 'PLA', 'silk'),
  ('bambu-petg-hf', 'bambu', 'PETG HF', 'PETG', 'basic'),
  ('polymaker-polyterra', 'polymaker', 'PolyTerra PLA', 'PLA', 'matte'),
  ('polymaker-polylite-pla', 'polymaker', 'PolyLite PLA', 'PLA', 'basic'),
  ('polymaker-polylite-petg', 'polymaker', 'PolyLite PETG', 'PETG', 'basic'),
  ('prusament-pla', 'prusament', 'Prusament PLA', 'PLA', 'basic'),
  ('prusament-petg', 'prusament', 'Prusament PETG', 'PETG', 'basic'),
  ('hatchbox-pla', 'hatchbox', 'PLA', 'PLA', 'basic'),
  ('esun-pla-plus', 'esun', 'PLA+', 'PLA+', 'basic'),
  ('esun-abs-plus', 'esun', 'ABS+', 'ABS', 'basic'),
  ('overture-pla', 'overture', 'PLA', 'PLA', 'basic'),
  ('overture-asa', 'overture', 'ASA', 'ASA', 'basic'),
  ('elegoo-pla', 'elegoo', 'PLA', 'PLA', 'basic'),
  ('sunlu-pla-matte', 'sunlu', 'PLA Matte', 'PLA', 'matte')
on conflict (id) do update set name = excluded.name, material = excluded.material, finish = excluded.finish;

insert into filaments (id, manufacturer_id, product_line_id, material, color_name, color_code, hex, hex_verified, finish, transparency, notes) values
  ('bambu-pla-basic-jade-white', 'bambu', 'bambu-pla-basic', 'PLA', 'Jade White', '10100', '#FFFFFF', true, 'basic', 'opaque', 'Bright, slightly cool white. The go-to base for pastels.'),
  ('bambu-pla-basic-black', 'bambu', 'bambu-pla-basic', 'PLA', 'Black', '10101', '#000000', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-cobalt-blue', 'bambu', 'bambu-pla-basic', 'PLA', 'Cobalt Blue', '10601', '#0056B8', true, 'basic', 'opaque', 'Very strong tint. A little goes a long way.'),
  ('bambu-pla-basic-red', 'bambu', 'bambu-pla-basic', 'PLA', 'Red', '10200', '#C12E1F', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-yellow', 'bambu', 'bambu-pla-basic', 'PLA', 'Yellow', '10400', '#F4EE2A', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-orange', 'bambu', 'bambu-pla-basic', 'PLA', 'Orange', '10300', '#FF6A13', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-bambu-green', 'bambu', 'bambu-pla-basic', 'PLA', 'Bambu Green', '10501', '#00AE42', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-magenta', 'bambu', 'bambu-pla-basic', 'PLA', 'Magenta', '10202', '#EC008C', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-cyan', 'bambu', 'bambu-pla-basic', 'PLA', 'Cyan', '10603', '#0086D6', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-purple', 'bambu', 'bambu-pla-basic', 'PLA', 'Purple', '10700', '#5E43B7', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-gray', 'bambu', 'bambu-pla-basic', 'PLA', 'Gray', '10103', '#8E9089', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-light-gray', 'bambu', 'bambu-pla-basic', 'PLA', 'Light Gray', '10104', '#D1D3D5', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-silver', 'bambu', 'bambu-pla-basic', 'PLA', 'Silver', '10102', '#A6A9AA', false, 'metallic', 'opaque', null),
  ('bambu-pla-basic-brown', 'bambu', 'bambu-pla-basic', 'PLA', 'Brown', '10800', '#9D432C', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-beige', 'bambu', 'bambu-pla-basic', 'PLA', 'Beige', '10201', '#F7E6DE', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-pink', 'bambu', 'bambu-pla-basic', 'PLA', 'Pink', '10203', '#F55A74', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-gold', 'bambu', 'bambu-pla-basic', 'PLA', 'Gold', '10401', '#E4BD68', false, 'metallic', 'opaque', null),
  ('bambu-pla-basic-mistletoe-green', 'bambu', 'bambu-pla-basic', 'PLA', 'Mistletoe Green', '10502', '#3F8E43', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-turquoise', 'bambu', 'bambu-pla-basic', 'PLA', 'Turquoise', '10605', '#00B1B7', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-indigo-purple', 'bambu', 'bambu-pla-basic', 'PLA', 'Indigo Purple', '10701', '#482960', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-maroon-red', 'bambu', 'bambu-pla-basic', 'PLA', 'Maroon Red', '10205', '#9D2235', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-blue-grey', 'bambu', 'bambu-pla-basic', 'PLA', 'Blue Grey', '10602', '#5B6579', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-sunflower-yellow', 'bambu', 'bambu-pla-basic', 'PLA', 'Sunflower Yellow', '10402', '#FEC600', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-cocoa-brown', 'bambu', 'bambu-pla-basic', 'PLA', 'Cocoa Brown', '10802', '#6F5034', false, 'basic', 'opaque', null),
  ('bambu-pla-matte-ivory-white', 'bambu', 'bambu-pla-matte', 'PLA', 'Ivory White', '11100', '#FFFFFF', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-charcoal', 'bambu', 'bambu-pla-matte', 'PLA', 'Charcoal', '11101', '#000000', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-ash-gray', 'bambu', 'bambu-pla-matte', 'PLA', 'Ash Gray', '11102', '#9B9EA0', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-lilac-purple', 'bambu', 'bambu-pla-matte', 'PLA', 'Lilac Purple', '11700', '#AE96D4', true, 'matte', 'opaque', null),
  ('bambu-pla-matte-sakura-pink', 'bambu', 'bambu-pla-matte', 'PLA', 'Sakura Pink', '11201', '#E8AFCF', true, 'matte', 'opaque', null),
  ('bambu-pla-matte-ice-blue', 'bambu', 'bambu-pla-matte', 'PLA', 'Ice Blue', '11601', '#A3D8E1', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-marine-blue', 'bambu', 'bambu-pla-matte', 'PLA', 'Marine Blue', '11600', '#0078BF', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-dark-blue', 'bambu', 'bambu-pla-matte', 'PLA', 'Dark Blue', '11602', '#042F56', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-scarlet-red', 'bambu', 'bambu-pla-matte', 'PLA', 'Scarlet Red', '11200', '#DE4343', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-mandarin-orange', 'bambu', 'bambu-pla-matte', 'PLA', 'Mandarin Orange', '11300', '#F99963', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-lemon-yellow', 'bambu', 'bambu-pla-matte', 'PLA', 'Lemon Yellow', '11400', '#F7D959', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-grass-green', 'bambu', 'bambu-pla-matte', 'PLA', 'Grass Green', '11500', '#61C680', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-apple-green', 'bambu', 'bambu-pla-matte', 'PLA', 'Apple Green', '11502', '#C2E189', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-desert-tan', 'bambu', 'bambu-pla-matte', 'PLA', 'Desert Tan', '11401', '#E8DBB7', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-latte-brown', 'bambu', 'bambu-pla-matte', 'PLA', 'Latte Brown', '11800', '#D3B7A7', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-dark-chocolate', 'bambu', 'bambu-pla-matte', 'PLA', 'Dark Chocolate', '11801', '#4D3324', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-terracotta', 'bambu', 'bambu-pla-matte', 'PLA', 'Terracotta', '11203', '#B15533', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-plum', 'bambu', 'bambu-pla-matte', 'PLA', 'Plum', '11204', '#851A52', false, 'matte', 'opaque', null),
  ('bambu-pla-silk-silk-gold', 'bambu', 'bambu-pla-silk', 'PLA', 'Silk Gold', '13400', '#F4A925', false, 'silk', 'opaque', null),
  ('bambu-pla-silk-silk-silver', 'bambu', 'bambu-pla-silk', 'PLA', 'Silk Silver', '13101', '#C8C8C8', false, 'silk', 'opaque', null),
  ('bambu-pla-silk-silk-mint', 'bambu', 'bambu-pla-silk', 'PLA', 'Silk Mint', '13501', '#96DCB9', false, 'silk', 'opaque', null),
  ('bambu-pla-silk-silk-rose-gold', 'bambu', 'bambu-pla-silk', 'PLA', 'Silk Rose Gold', '13201', '#BA9594', false, 'silk', 'opaque', null),
  ('bambu-petg-hf-white', 'bambu', 'bambu-petg-hf', 'PETG', 'White', '33100', '#FFFFFF', false, 'basic', 'opaque', null),
  ('bambu-petg-hf-black', 'bambu', 'bambu-petg-hf', 'PETG', 'Black', '33101', '#000000', false, 'basic', 'opaque', null),
  ('bambu-petg-hf-red', 'bambu', 'bambu-petg-hf', 'PETG', 'Red', '33200', '#EB3A3A', false, 'basic', 'opaque', null),
  ('bambu-petg-hf-blue', 'bambu', 'bambu-petg-hf', 'PETG', 'Blue', '33600', '#002E96', false, 'basic', 'opaque', null),
  ('bambu-petg-hf-yellow', 'bambu', 'bambu-petg-hf', 'PETG', 'Yellow', '33400', '#FFD00B', false, 'basic', 'opaque', null),
  ('bambu-petg-hf-green', 'bambu', 'bambu-petg-hf', 'PETG', 'Green', '33500', '#00AE42', false, 'basic', 'opaque', null),
  ('polymaker-polyterra-cotton-white', 'polymaker', 'polymaker-polyterra', 'PLA', 'Cotton White', null, '#E6DDDB', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-charcoal-black', 'polymaker', 'polymaker-polyterra', 'PLA', 'Charcoal Black', null, '#2B2B2D', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-fossil-grey', 'polymaker', 'polymaker-polyterra', 'PLA', 'Fossil Grey', null, '#7F7F7F', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-lava-red', 'polymaker', 'polymaker-polyterra', 'PLA', 'Lava Red', null, '#C8102E', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-sunrise-orange', 'polymaker', 'polymaker-polyterra', 'PLA', 'Sunrise Orange', null, '#F68D2E', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-savannah-yellow', 'polymaker', 'polymaker-polyterra', 'PLA', 'Savannah Yellow', null, '#F1C232', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-forest-green', 'polymaker', 'polymaker-polyterra', 'PLA', 'Forest Green', null, '#3E7D4C', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-arctic-teal', 'polymaker', 'polymaker-polyterra', 'PLA', 'Arctic Teal', null, '#2BA8A4', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-ocean-blue', 'polymaker', 'polymaker-polyterra', 'PLA', 'Ocean Blue', null, '#1D4E89', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-lavender-purple', 'polymaker', 'polymaker-polyterra', 'PLA', 'Lavender Purple', null, '#A389C4', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-peach', 'polymaker', 'polymaker-polyterra', 'PLA', 'Peach', null, '#F5B79D', false, 'matte', 'opaque', null),
  ('polymaker-polyterra-muted-red', 'polymaker', 'polymaker-polyterra', 'PLA', 'Muted Red', null, '#A0453E', false, 'matte', 'opaque', null),
  ('polymaker-polylite-pla-white', 'polymaker', 'polymaker-polylite-pla', 'PLA', 'White', null, '#F7F7F5', false, 'basic', 'opaque', null),
  ('polymaker-polylite-pla-black', 'polymaker', 'polymaker-polylite-pla', 'PLA', 'Black', null, '#1A1A1A', false, 'basic', 'opaque', null),
  ('polymaker-polylite-pla-blue', 'polymaker', 'polymaker-polylite-pla', 'PLA', 'Blue', null, '#1F5AA6', false, 'basic', 'opaque', null),
  ('polymaker-polylite-pla-red', 'polymaker', 'polymaker-polylite-pla', 'PLA', 'Red', null, '#D2232A', false, 'basic', 'opaque', null),
  ('polymaker-polylite-pla-teal', 'polymaker', 'polymaker-polylite-pla', 'PLA', 'Teal', null, '#00857C', false, 'basic', 'opaque', null),
  ('polymaker-polylite-pla-translucent-blue', 'polymaker', 'polymaker-polylite-pla', 'PLA', 'Translucent Blue', null, '#3A7BD5', false, 'translucent', 'translucent', null),
  ('polymaker-polylite-petg-white', 'polymaker', 'polymaker-polylite-petg', 'PETG', 'White', null, '#F5F5F3', false, 'basic', 'opaque', null),
  ('polymaker-polylite-petg-black', 'polymaker', 'polymaker-polylite-petg', 'PETG', 'Black', null, '#1C1C1C', false, 'basic', 'opaque', null),
  ('polymaker-polylite-petg-grey', 'polymaker', 'polymaker-polylite-petg', 'PETG', 'Grey', null, '#8A8D8F', false, 'basic', 'opaque', null),
  ('prusament-pla-vanilla-white', 'prusament', 'prusament-pla', 'PLA', 'Vanilla White', null, '#F3EDE0', false, 'basic', 'opaque', null),
  ('prusament-pla-galaxy-black', 'prusament', 'prusament-pla', 'PLA', 'Galaxy Black', null, '#1D1D21', false, 'sparkle', 'opaque', null),
  ('prusament-pla-prusa-orange', 'prusament', 'prusament-pla', 'PLA', 'Prusa Orange', null, '#FA6831', false, 'basic', 'opaque', null),
  ('prusament-pla-azure-blue', 'prusament', 'prusament-pla', 'PLA', 'Azure Blue', null, '#2E7FD1', false, 'basic', 'opaque', null),
  ('prusament-pla-lipstick-red', 'prusament', 'prusament-pla', 'PLA', 'Lipstick Red', null, '#C7162B', false, 'basic', 'opaque', null),
  ('prusament-pla-pistachio-green', 'prusament', 'prusament-pla', 'PLA', 'Pistachio Green', null, '#9BC33C', false, 'basic', 'opaque', null),
  ('prusament-pla-mystic-green', 'prusament', 'prusament-pla', 'PLA', 'Mystic Green', null, '#3C7D5A', false, 'basic', 'opaque', null),
  ('prusament-pla-royal-blue', 'prusament', 'prusament-pla', 'PLA', 'Royal Blue', null, '#22339A', false, 'basic', 'opaque', null),
  ('prusament-pla-pineapple-yellow', 'prusament', 'prusament-pla', 'PLA', 'Pineapple Yellow', null, '#F7D117', false, 'basic', 'opaque', null),
  ('prusament-pla-lilac-purple', 'prusament', 'prusament-pla', 'PLA', 'Lilac Purple', null, '#B48BC5', false, 'basic', 'opaque', null),
  ('prusament-petg-signal-white', 'prusament', 'prusament-petg', 'PETG', 'Signal White', null, '#F4F4F4', false, 'basic', 'opaque', null),
  ('prusament-petg-jet-black', 'prusament', 'prusament-petg', 'PETG', 'Jet Black', null, '#141414', false, 'basic', 'opaque', null),
  ('prusament-petg-ultramarine-blue', 'prusament', 'prusament-petg', 'PETG', 'Ultramarine Blue', null, '#1E3E9C', false, 'basic', 'opaque', null),
  ('hatchbox-pla-white', 'hatchbox', 'hatchbox-pla', 'PLA', 'White', null, '#FAFAFA', false, 'basic', 'opaque', null),
  ('hatchbox-pla-black', 'hatchbox', 'hatchbox-pla', 'PLA', 'Black', null, '#121212', false, 'basic', 'opaque', null),
  ('hatchbox-pla-true-blue', 'hatchbox', 'hatchbox-pla', 'PLA', 'True Blue', null, '#1A49B6', false, 'basic', 'opaque', null),
  ('hatchbox-pla-red', 'hatchbox', 'hatchbox-pla', 'PLA', 'Red', null, '#C81F2F', false, 'basic', 'opaque', null),
  ('hatchbox-pla-yellow', 'hatchbox', 'hatchbox-pla', 'PLA', 'Yellow', null, '#FFD60A', false, 'basic', 'opaque', null),
  ('hatchbox-pla-purple', 'hatchbox', 'hatchbox-pla', 'PLA', 'Purple', null, '#5F2C91', false, 'basic', 'opaque', null),
  ('hatchbox-pla-pink', 'hatchbox', 'hatchbox-pla', 'PLA', 'Pink', null, '#F38FB4', false, 'basic', 'opaque', null),
  ('hatchbox-pla-cool-gray', 'hatchbox', 'hatchbox-pla', 'PLA', 'Cool Gray', null, '#8C949B', false, 'basic', 'opaque', null),
  ('esun-pla-plus-cold-white', 'esun', 'esun-pla-plus', 'PLA+', 'Cold White', null, '#F6F8FA', false, 'basic', 'opaque', null),
  ('esun-pla-plus-black', 'esun', 'esun-pla-plus', 'PLA+', 'Black', null, '#141414', false, 'basic', 'opaque', null),
  ('esun-pla-plus-fire-engine-red', 'esun', 'esun-pla-plus', 'PLA+', 'Fire Engine Red', null, '#C51F25', false, 'basic', 'opaque', null),
  ('esun-pla-plus-light-blue', 'esun', 'esun-pla-plus', 'PLA+', 'Light Blue', null, '#7DB4E6', false, 'basic', 'opaque', null),
  ('esun-pla-plus-peak-green', 'esun', 'esun-pla-plus', 'PLA+', 'Peak Green', null, '#3C9A44', false, 'basic', 'opaque', null),
  ('esun-pla-plus-magenta', 'esun', 'esun-pla-plus', 'PLA+', 'Magenta', null, '#D0157D', false, 'basic', 'opaque', null),
  ('esun-pla-plus-beige', 'esun', 'esun-pla-plus', 'PLA+', 'Beige', null, '#E3CFAE', false, 'basic', 'opaque', null),
  ('esun-pla-plus-skin', 'esun', 'esun-pla-plus', 'PLA+', 'Skin', null, '#F1C7A5', false, 'basic', 'opaque', null),
  ('esun-abs-plus-white', 'esun', 'esun-abs-plus', 'ABS', 'White', null, '#F4F4F2', false, 'basic', 'opaque', null),
  ('esun-abs-plus-black', 'esun', 'esun-abs-plus', 'ABS', 'Black', null, '#151515', false, 'basic', 'opaque', null),
  ('esun-abs-plus-red', 'esun', 'esun-abs-plus', 'ABS', 'Red', null, '#C02028', false, 'basic', 'opaque', null),
  ('esun-abs-plus-blue', 'esun', 'esun-abs-plus', 'ABS', 'Blue', null, '#1C4FA6', false, 'basic', 'opaque', null),
  ('overture-pla-space-gray', 'overture', 'overture-pla', 'PLA', 'Space Gray', null, '#55595C', false, 'basic', 'opaque', null),
  ('overture-pla-rock-white', 'overture', 'overture-pla', 'PLA', 'Rock White', null, '#EEEDE8', false, 'basic', 'opaque', null),
  ('overture-pla-black', 'overture', 'overture-pla', 'PLA', 'Black', null, '#151515', false, 'basic', 'opaque', null),
  ('overture-pla-blue', 'overture', 'overture-pla', 'PLA', 'Blue', null, '#2155B3', false, 'basic', 'opaque', null),
  ('overture-pla-red', 'overture', 'overture-pla', 'PLA', 'Red', null, '#D12A2A', false, 'basic', 'opaque', null),
  ('overture-pla-yellow', 'overture', 'overture-pla', 'PLA', 'Yellow', null, '#FDE02F', false, 'basic', 'opaque', null),
  ('overture-asa-white', 'overture', 'overture-asa', 'ASA', 'White', null, '#F2F2F0', false, 'basic', 'opaque', null),
  ('overture-asa-black', 'overture', 'overture-asa', 'ASA', 'Black', null, '#161616', false, 'basic', 'opaque', null),
  ('overture-asa-red', 'overture', 'overture-asa', 'ASA', 'Red', null, '#BF2228', false, 'basic', 'opaque', null),
  ('overture-asa-blue', 'overture', 'overture-asa', 'ASA', 'Blue', null, '#1F4FA5', false, 'basic', 'opaque', null),
  ('elegoo-pla-white', 'elegoo', 'elegoo-pla', 'PLA', 'White', null, '#F8F8F6', false, 'basic', 'opaque', null),
  ('elegoo-pla-black', 'elegoo', 'elegoo-pla', 'PLA', 'Black', null, '#151515', false, 'basic', 'opaque', null),
  ('elegoo-pla-red', 'elegoo', 'elegoo-pla', 'PLA', 'Red', null, '#C9252B', false, 'basic', 'opaque', null),
  ('elegoo-pla-blue', 'elegoo', 'elegoo-pla', 'PLA', 'Blue', null, '#1D57B3', false, 'basic', 'opaque', null),
  ('elegoo-pla-green', 'elegoo', 'elegoo-pla', 'PLA', 'Green', null, '#2D9C49', false, 'basic', 'opaque', null),
  ('sunlu-pla-matte-matte-white', 'sunlu', 'sunlu-pla-matte', 'PLA', 'Matte White', null, '#EFECE6', false, 'matte', 'opaque', null),
  ('sunlu-pla-matte-matte-black', 'sunlu', 'sunlu-pla-matte', 'PLA', 'Matte Black', null, '#1E1E1E', false, 'matte', 'opaque', null),
  ('sunlu-pla-matte-matte-mint', 'sunlu', 'sunlu-pla-matte', 'PLA', 'Matte Mint', null, '#9FD6BF', false, 'matte', 'opaque', null),
  ('sunlu-pla-matte-matte-caramel', 'sunlu', 'sunlu-pla-matte', 'PLA', 'Matte Caramel', null, '#B98252', false, 'matte', 'opaque', null)
on conflict (id) do update set color_name = excluded.color_name, color_code = excluded.color_code, hex = excluded.hex, hex_verified = excluded.hex_verified, finish = excluded.finish, transparency = excluded.transparency, notes = excluded.notes;
