-- SpoolShare filament catalog (Bambu Lab). Generated from src/lib/api/mock/seed/catalog.ts. Safe to re-run.

insert into manufacturers (id, name, website) values
  ('bambu', 'Bambu Lab', 'https://bambulab.com')
on conflict (id) do update set name = excluded.name, website = excluded.website;

insert into product_lines (id, manufacturer_id, name, material, finish) values
  ('bambu-pla-basic', 'bambu', 'PLA Basic', 'PLA', 'basic'),
  ('bambu-pla-matte', 'bambu', 'PLA Matte', 'PLA', 'matte'),
  ('bambu-pla-silk', 'bambu', 'PLA Silk+', 'PLA', 'silk'),
  ('bambu-pla-translucent', 'bambu', 'PLA Translucent', 'PLA', 'translucent'),
  ('bambu-petg-hf', 'bambu', 'PETG HF', 'PETG', 'basic')
on conflict (id) do update set name = excluded.name, material = excluded.material, finish = excluded.finish;

insert into filaments (id, manufacturer_id, product_line_id, material, color_name, color_code, hex, hex_verified, finish, transparency, notes) values
  ('bambu-pla-basic-jade-white', 'bambu', 'bambu-pla-basic', 'PLA', 'Jade White', '10100', '#FFFFFF', true, 'basic', 'opaque', 'Bright, slightly cool white. The go-to base for pastels.'),
  ('bambu-pla-basic-black', 'bambu', 'bambu-pla-basic', 'PLA', 'Black', '10101', '#000000', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-cobalt-blue', 'bambu', 'bambu-pla-basic', 'PLA', 'Cobalt Blue', '10601', '#0056B8', true, 'basic', 'opaque', 'Very strong tint. A little goes a long way.'),
  ('bambu-pla-basic-red', 'bambu', 'bambu-pla-basic', 'PLA', 'Red', '10200', '#C12E1F', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-yellow', 'bambu', 'bambu-pla-basic', 'PLA', 'Yellow', '10400', '#F4EE2A', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-orange', 'bambu', 'bambu-pla-basic', 'PLA', 'Orange', '10300', '#FF6A13', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-bambu-green', 'bambu', 'bambu-pla-basic', 'PLA', 'Bambu Green', '10501', '#00AE42', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-magenta', 'bambu', 'bambu-pla-basic', 'PLA', 'Magenta', '10202', '#EC008C', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-cyan', 'bambu', 'bambu-pla-basic', 'PLA', 'Cyan', '10603', '#0086D6', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-purple', 'bambu', 'bambu-pla-basic', 'PLA', 'Purple', '10700', '#5E43B7', true, 'basic', 'opaque', null),
  ('bambu-pla-basic-gray', 'bambu', 'bambu-pla-basic', 'PLA', 'Gray', '10103', '#8E9089', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-light-gray', 'bambu', 'bambu-pla-basic', 'PLA', 'Light Gray', '10104', '#D1D3D5', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-silver', 'bambu', 'bambu-pla-basic', 'PLA', 'Silver', '10102', '#A6A9AA', false, 'metallic', 'opaque', null),
  ('bambu-pla-basic-brown', 'bambu', 'bambu-pla-basic', 'PLA', 'Brown', '10800', '#9D432C', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-beige', 'bambu', 'bambu-pla-basic', 'PLA', 'Beige', '10201', '#F7E6DE', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-pink', 'bambu', 'bambu-pla-basic', 'PLA', 'Pink', '10203', '#F55A74', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-gold', 'bambu', 'bambu-pla-basic', 'PLA', 'Gold', '10401', '#E4BD68', false, 'metallic', 'opaque', null),
  ('bambu-pla-basic-mistletoe-green', 'bambu', 'bambu-pla-basic', 'PLA', 'Mistletoe Green', '10502', '#3F8E43', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-turquoise', 'bambu', 'bambu-pla-basic', 'PLA', 'Turquoise', '10605', '#00B1B7', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-indigo-purple', 'bambu', 'bambu-pla-basic', 'PLA', 'Indigo Purple', '10701', '#482960', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-maroon-red', 'bambu', 'bambu-pla-basic', 'PLA', 'Maroon Red', '10205', '#9D2235', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-blue-grey', 'bambu', 'bambu-pla-basic', 'PLA', 'Blue Grey', '10602', '#5B6579', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-sunflower-yellow', 'bambu', 'bambu-pla-basic', 'PLA', 'Sunflower Yellow', '10402', '#FEC600', false, 'basic', 'opaque', null),
  ('bambu-pla-basic-cocoa-brown', 'bambu', 'bambu-pla-basic', 'PLA', 'Cocoa Brown', '10802', '#6F5034', false, 'basic', 'opaque', null),
  ('bambu-pla-matte-ivory-white', 'bambu', 'bambu-pla-matte', 'PLA', 'Ivory White', '11100', '#FFFFFF', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-charcoal', 'bambu', 'bambu-pla-matte', 'PLA', 'Charcoal', '11101', '#000000', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-ash-gray', 'bambu', 'bambu-pla-matte', 'PLA', 'Ash Gray', '11102', '#9B9EA0', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-lilac-purple', 'bambu', 'bambu-pla-matte', 'PLA', 'Lilac Purple', '11700', '#AE96D4', true, 'matte', 'opaque', null),
  ('bambu-pla-matte-sakura-pink', 'bambu', 'bambu-pla-matte', 'PLA', 'Sakura Pink', '11201', '#E8AFCF', true, 'matte', 'opaque', null),
  ('bambu-pla-matte-ice-blue', 'bambu', 'bambu-pla-matte', 'PLA', 'Ice Blue', '11601', '#A3D8E1', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-marine-blue', 'bambu', 'bambu-pla-matte', 'PLA', 'Marine Blue', '11600', '#0078BF', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-dark-blue', 'bambu', 'bambu-pla-matte', 'PLA', 'Dark Blue', '11602', '#042F56', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-scarlet-red', 'bambu', 'bambu-pla-matte', 'PLA', 'Scarlet Red', '11200', '#DE4343', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-mandarin-orange', 'bambu', 'bambu-pla-matte', 'PLA', 'Mandarin Orange', '11300', '#F99963', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-lemon-yellow', 'bambu', 'bambu-pla-matte', 'PLA', 'Lemon Yellow', '11400', '#F7D959', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-grass-green', 'bambu', 'bambu-pla-matte', 'PLA', 'Grass Green', '11500', '#61C680', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-apple-green', 'bambu', 'bambu-pla-matte', 'PLA', 'Apple Green', '11502', '#C2E189', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-desert-tan', 'bambu', 'bambu-pla-matte', 'PLA', 'Desert Tan', '11401', '#E8DBB7', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-latte-brown', 'bambu', 'bambu-pla-matte', 'PLA', 'Latte Brown', '11800', '#D3B7A7', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-dark-chocolate', 'bambu', 'bambu-pla-matte', 'PLA', 'Dark Chocolate', '11801', '#4D3324', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-terracotta', 'bambu', 'bambu-pla-matte', 'PLA', 'Terracotta', '11203', '#B15533', false, 'matte', 'opaque', null),
  ('bambu-pla-matte-plum', 'bambu', 'bambu-pla-matte', 'PLA', 'Plum', '11204', '#851A52', false, 'matte', 'opaque', null),
  ('bambu-pla-silk-silk-gold', 'bambu', 'bambu-pla-silk', 'PLA', 'Silk Gold', '13400', '#F4A925', false, 'silk', 'opaque', null),
  ('bambu-pla-silk-silk-silver', 'bambu', 'bambu-pla-silk', 'PLA', 'Silk Silver', '13101', '#C8C8C8', false, 'silk', 'opaque', null),
  ('bambu-pla-silk-silk-mint', 'bambu', 'bambu-pla-silk', 'PLA', 'Silk Mint', '13501', '#96DCB9', false, 'silk', 'opaque', null),
  ('bambu-pla-silk-silk-rose-gold', 'bambu', 'bambu-pla-silk', 'PLA', 'Silk Rose Gold', '13201', '#BA9594', false, 'silk', 'opaque', null),
  ('bambu-pla-translucent-translucent-clear', 'bambu', 'bambu-pla-translucent', 'PLA', 'Translucent Clear', null, '#F2F4F5', false, 'translucent', 'clear', null),
  ('bambu-pla-translucent-translucent-blue', 'bambu', 'bambu-pla-translucent', 'PLA', 'Translucent Blue', null, '#4A8FD8', false, 'translucent', 'translucent', null),
  ('bambu-pla-translucent-translucent-red', 'bambu', 'bambu-pla-translucent', 'PLA', 'Translucent Red', null, '#D93B3B', false, 'translucent', 'translucent', null),
  ('bambu-petg-hf-white', 'bambu', 'bambu-petg-hf', 'PETG', 'White', '33100', '#FFFFFF', false, 'basic', 'opaque', null),
  ('bambu-petg-hf-black', 'bambu', 'bambu-petg-hf', 'PETG', 'Black', '33101', '#000000', false, 'basic', 'opaque', null),
  ('bambu-petg-hf-red', 'bambu', 'bambu-petg-hf', 'PETG', 'Red', '33200', '#EB3A3A', false, 'basic', 'opaque', null),
  ('bambu-petg-hf-blue', 'bambu', 'bambu-petg-hf', 'PETG', 'Blue', '33600', '#002E96', false, 'basic', 'opaque', null),
  ('bambu-petg-hf-yellow', 'bambu', 'bambu-petg-hf', 'PETG', 'Yellow', '33400', '#FFD00B', false, 'basic', 'opaque', null),
  ('bambu-petg-hf-green', 'bambu', 'bambu-petg-hf', 'PETG', 'Green', '33500', '#00AE42', false, 'basic', 'opaque', null)
on conflict (id) do update set color_name = excluded.color_name, color_code = excluded.color_code, hex = excluded.hex, hex_verified = excluded.hex_verified, finish = excluded.finish, transparency = excluded.transparency, notes = excluded.notes;
