import { chromium } from 'playwright-core'
const S = process.argv[2], W = Number(process.argv[3] ?? 1280), dark = process.argv[4] === 'dark'
const b = await chromium.launch({ channel: 'chrome' })
const p = await b.newPage({ viewport: { width: W, height: 900 }, colorScheme: dark ? 'dark' : 'light' })
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => m.type()==='error' && errs.push(m.text()))
const P = '/create?prefill=' + encodeURIComponent(JSON.stringify({ components: [{ filamentId: 'bambu-pla-basic-jade-white', parts: 3 }, { filamentId: 'bambu-pla-basic-cobalt-blue', parts: 1 }] }))
await p.goto('http://localhost:5199' + P, { waitUntil: 'networkidle' })
await p.fill('#r-name', 'Dusty Purple')
const next = () => p.click('button:has-text("Next")')
await next(); await next(); await next() // -> stages
await p.click('button:has-text("Add Mixing Stage")')
await p.waitForTimeout(2500)
console.log('URL after autosave:', p.url())
const heading = await p.textContent('main h2'); console.log('step heading:', heading)
// stage 2: add white and red
const stage2 = p.locator('section[aria-labelledby^="stage-"]').nth(1)
await stage2.locator('button:has-text("Add input")').click()
await stage2.locator('button:has-text("Add input")').click()
await p.waitForTimeout(200)
const selects = stage2.locator('select')
console.log('stage2 inputs:', await selects.count())
// set 3rd input to red via catalog option: red not in palette -> use picker
await selects.nth(2).selectOption('__add__')
await p.waitForTimeout(400)
await p.fill('dialog[open] input[type=search]', 'bambu red')
await p.waitForTimeout(400)
await p.click('dialog[open] li:has-text("PLA Basic") >> text=Red >> nth=0')
await p.waitForTimeout(300)
await stage2.locator('input[id$="-ratio"]').fill('1:2:1')
await p.waitForTimeout(300)
await p.screenshot({ path: `${S}/create-flow-stages-${W}${dark?'-dark':''}.png`, fullPage: true })
await next(); await next(); await next() // instructions, photos, review
await p.waitForTimeout(400)
await p.screenshot({ path: `${S}/create-flow-review-${W}${dark?'-dark':''}.png`, fullPage: true })
await next()
await p.click('button:has-text("Publish recipe")')
await p.waitForTimeout(1500)
await p.screenshot({ path: `${S}/create-flow-done-${W}${dark?'-dark':''}.png` })
console.log('final text:', (await p.textContent('main h2'))?.trim())
console.log('ERRORS', errs)
await b.close()
